/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package manoloaccess;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class loginPage extends javax.swing.JFrame {

    /**
     * Creates new form loginPage
     */
    PreparedStatement ps = null;
    Connection con;
    
    public loginPage() {
        initComponents();
        String url = "jdbc:mysql://localhost:3306/db_ticketing";
        String user = "root";
        String pass = "";
        try {
            con = DriverManager.getConnection(url, user, pass);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Database connection failed: " + ex.getMessage());
        }
    }


    private void login(String username, String password) {
        try (PreparedStatement ps = con.prepareStatement(
                "SELECT customer_id FROM customers WHERE username = ? AND password = ?")) {
            ps.setString(1, username);
            ps.setString(2, password); // Note: In production, hash passwords
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    int customerId = rs.getInt("customer_id");
                    UserSession.setCustomerId(customerId);
                    JOptionPane.showMessageDialog(null, "Login successful!");
                    new UserInterface().setVisible(true); // Navigate to UserInterface
                    dispose(); // Close LoginPage
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid username or password.");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Login error: " + e.getMessage());
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        U_Username = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        U_LoginButton = new javax.swing.JButton();
        U_Password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        UsernameLabel1 = new javax.swing.JLabel();
        A_Username = new javax.swing.JTextField();
        PasswordLabel1 = new javax.swing.JLabel();
        A_Password = new javax.swing.JPasswordField();
        A_LoginButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 550));

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(500, 550));

        jPanel3.setPreferredSize(new java.awt.Dimension(500, 550));

        UsernameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        UsernameLabel.setText("Username");

        U_Username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        U_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_UsernameActionPerformed(evt);
            }
        });

        PasswordLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PasswordLabel.setText("Password");

        U_LoginButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        U_LoginButton.setText("LOGIN");
        U_LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_LoginButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(U_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(U_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameLabel))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(U_LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(192, 192, 192))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(U_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(U_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(U_LoginButton)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(117, 117, 117))
        );

        jTabbedPane1.addTab("User", jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(500, 550));

        UsernameLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        UsernameLabel1.setText("Username");

        A_Username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_UsernameActionPerformed(evt);
            }
        });

        PasswordLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PasswordLabel1.setText("Password");

        A_LoginButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_LoginButton.setText("LOGIN");
        A_LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(A_LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(196, 196, 196))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PasswordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UsernameLabel1))
                            .addGap(34, 34, 34)))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(UsernameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(PasswordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(A_LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jTabbedPane1.addTab("Admin", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1144, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1144, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void U_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U_UsernameActionPerformed

    private void U_LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_LoginButtonActionPerformed
        // TODO add your handling code here:
     String username = U_Username.getText().trim();
    String password = new String(U_Password.getPassword()).trim();

    // Validation
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Username and password are required.");
        return;
    }

    if (con == null) {
        JOptionPane.showMessageDialog(null, "Database connection is not established.");
        return;
    }

    System.out.println("Trying login with username: " + username + ", password: " + password);

    try {
        String sql = "SELECT customer_id, name FROM customers WHERE username = ? AND password = ?";
        try (PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, username);
            ps.setString(2, password);  // Use hashed password if your DB stores it hashed

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    int customerId = rs.getInt("customer_id");
                    String customerName = rs.getString("name");

                    System.out.println("Login successful for user: " + customerName + " (ID: " + customerId + ")");
                    JOptionPane.showMessageDialog(null, "Login successful! Welcome, " + customerName);

                    // HIGHLIGHT: Store customerId in UserSession instead of setting it directly in UserInterface
                    UserSession.setCustomerId(customerId);
                    UserInterface userint = new UserInterface();
                    userint.setVisible(true);

                    dispose(); // Close login form
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid username or password.");
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();  // Log full error
        JOptionPane.showMessageDialog(null, "Error during login: " + e.getMessage());
    }
    }//GEN-LAST:event_U_LoginButtonActionPerformed

    private void A_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_UsernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_A_UsernameActionPerformed

    private void A_LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_LoginButtonActionPerformed
        // TODO add your handling code here:
       String validUsername = "admin";
    String validPassword = "Admin@123";

    // Get input from text fields
    String enteredUsername = A_Username.getText();
    String enteredPassword = new String(A_Password.getPassword()); // if using JPasswordField

    // Validate credentials
    if (enteredUsername.equals(validUsername) && enteredPassword.equals(validPassword)) {
        // Login success
        AdminInterface adint = new AdminInterface();
        adint.setVisible(true);
        dispose(); // Close the login window
    } else {
        // Login failed
        JOptionPane.showMessageDialog(this, "Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_A_LoginButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       Registration register = new Registration();
       register.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_LoginButton;
    private javax.swing.JPasswordField A_Password;
    private javax.swing.JTextField A_Username;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JButton U_LoginButton;
    private javax.swing.JPasswordField U_Password;
    private javax.swing.JTextField U_Username;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel UsernameLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
