/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package manoloaccess;

import java.awt.Image;
import java.io.FileOutputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    PreparedStatement ps = null;
    String path2 = null;
    Connection con;
    
    private int customerId;

    // Add this method
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
    
    public UserInterface() {
        initComponents();
        setLocationRelativeTo(null);
        
        String url = "jdbc:mysql://localhost:3306/db_ticketing";
        String user = "root";
        String pass = "";
        try {
            con = DriverManager.getConnection(url,user,pass);
            
        } catch (Exception ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }
    
    
    
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EventImageContainer = new javax.swing.JLabel();
        BuyTicket_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Venue = new javax.swing.JTextField();
        Description = new javax.swing.JTextField();
        Category = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_events = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ViewButton = new javax.swing.JButton();
        OrdersButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EventImageContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BuyTicket_Button.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BuyTicket_Button.setText("BUY TICKET");
        BuyTicket_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyTicket_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Title");

        Title.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Date");

        Date.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Venue");

        Venue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        Description.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        Category.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Category");

        tbl_events.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "event_id", "venue", "event", "date", "description", "category"
            }
        ));
        tbl_events.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_eventsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_events);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("UPCOMING EVENTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BuyTicket_Button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EventImageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(25, 25, 25)
                                .addComponent(Venue))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Date)
                                    .addComponent(Description, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(Title)
                                    .addComponent(Category))))
                        .addGap(409, 409, 409))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Venue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(EventImageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BuyTicket_Button)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setForeground(new java.awt.Color(102, 102, 0));

        ViewButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ViewButton.setText("View Events");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        OrdersButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        OrdersButton.setText("Orders");
        OrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewButton)
                .addGap(18, 18, 18)
                .addComponent(OrdersButton)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewButton)
                    .addComponent(OrdersButton)
                    .addComponent(logoutButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) tbl_events.getModel();
model.setRowCount(0); // Clear existing rows

String fetchQuery = "SELECT e.event_id, v.name AS venue_name, e.name, e.event_date, e.description, e.image_data, e.category FROM events e JOIN venues v ON e.venue_id = v.venue_id";
try {
    PreparedStatement pst = con.prepareStatement(fetchQuery);
    ResultSet rs = pst.executeQuery();

    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getString("event_id"),     // COLUMN 0 = event_id (IMPORTANT!)
            rs.getString("venue_name"),
            rs.getString("name"),
            rs.getString("event_date"),
            rs.getString("description"),
            rs.getString("category")
            // Note: Skipping image for the table view
        });
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_ViewButtonActionPerformed

    private void tbl_eventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_eventsMouseClicked
        // TODO add your handling code here:
      int r = tbl_events.getSelectedRow();

    if (r >= 0) {
        Object eventIdObj = tbl_events.getModel().getValueAt(r, 0); // COLUMN 0 = event_id

        if (eventIdObj != null) {
            String eventId = eventIdObj.toString();
            String sql = "SELECT e.event_id, v.name AS venue_name, e.name, e.event_date, e.description, e.image_data, e.category " +
                         "FROM events e JOIN venues v ON e.venue_id = v.venue_id WHERE e.event_id = ?";

            try {
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, eventId);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    // Fetch data
                    String name = rs.getString("name");
                    String eventDate = rs.getString("event_date");
                    String desc = rs.getString("description");
                    String category = rs.getString("category");
                    String venueName = rs.getString("venue_name");
                    Blob image = rs.getBlob("image_data");

                    // Convert Blob to byte array and save
                    byte[] bytea = image.getBytes(1, (int) image.length());
                    String path = "C:\\Users\\Admin\\Documents\\NetBeansProjects\\manoloAccess\\src\\mysqltonetbeans\\images\\img.jpg";
                    FileOutputStream fos = new FileOutputStream(path);
                    fos.write(bytea);
                    fos.close();

                    // Set values to UI fields
                    Title.setText(name);
                    Date.setText(eventDate);
                    Description.setText(desc);
                    Category.setText(category);
                    Venue.setText(venueName);

                    // Display image
                    ImageIcon icon = new ImageIcon(bytea);
                    Image scaled = icon.getImage().getScaledInstance(
                        EventImageContainer.getWidth(),
                        EventImageContainer.getHeight(),
                        Image.SCALE_SMOOTH
                    );
                    EventImageContainer.setIcon(new ImageIcon(scaled));
                } else {
                    JOptionPane.showMessageDialog(null, "No event found with that ID.");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selected row has no event_id.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please select a row first.");
    }
    }//GEN-LAST:event_tbl_eventsMouseClicked

    private void BuyTicket_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyTicket_ButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_events.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select an event first.");
        return;
    }

    try {
        String eventIdStr = tbl_events.getValueAt(selectedRow, 0).toString(); // column 0 = event_id
        int selectedEventId = Integer.parseInt(eventIdStr);
        String sql = "SELECT e.*, v.name AS venue_name, t.ticket_type, t.seat_section, t.price, t.tickets_left " +
                     "FROM events e " +
                     "LEFT JOIN venues v ON e.venue_id = v.venue_id " +
                     "LEFT JOIN tickets t ON e.event_id = t.event_id " +
                     "WHERE e.event_id = ?";
        
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, selectedEventId);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int customerId = UserSession.getCustomerId();
            if (customerId <= 0) {
                JOptionPane.showMessageDialog(null, "No customer logged in. Please log in first.");
                return;
            }

            Reservation reservation = new Reservation();
            reservation.setEventData(
                selectedEventId,
                rs.getBytes("image_data"),
                rs.getString("name"),
                rs.getString("event_date"),
                rs.getString("description"),
                rs.getString("category"),
                rs.getString("venue_name"),
                rs.getString("ticket_type"),
                rs.getString("seat_section"),
                rs.getDouble("price"),
                rs.getInt("tickets_left")
            );
            reservation.setVisible(true);

            // ✅ Dispose current frame after opening the reservation window
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Event details not found.");
        }

        rs.close();
        ps.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_BuyTicket_ButtonActionPerformed

    private void OrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersButtonActionPerformed
        // TODO add your handling code here:
       Orders orders = new Orders();
       orders.setVisible(true);
       dispose();
    }//GEN-LAST:event_OrdersButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        loginPage login = new loginPage();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    private String imagePath;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuyTicket_Button;
    private javax.swing.JTextField Category;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Description;
    private javax.swing.JLabel EventImageContainer;
    private javax.swing.JButton OrdersButton;
    private javax.swing.JTextField Title;
    private javax.swing.JTextField Venue;
    private javax.swing.JButton ViewButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTable tbl_events;
    // End of variables declaration//GEN-END:variables
}
